---
title: "Preliminary Analysis - Research in Health Economics"
author: "Ammarah Ahmed"
date: ""
header-includes:
  - \usepackage{booktabs}
output: 
  bookdown::pdf_document2:
    fig_caption: yes
    toc: false
---

```{r setup, include=FALSE}
pacman::p_load(Matching, tidyverse, ggplot2, dplyr, lubridate, stringr, readxl, readr, data.table, gdata, scales, kableExtra, modelsummary, fixest, imputeTS, rdrobust, rddensity)
```

```{r, warning = FALSE, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning = FALSE)
```

```{r}
load("finalproject.Rdata")
```

# Data

# Data Analysis 

```{r, include=FALSE}
sum_stat
```

```{r table1, include=T, eval=T, echo=F}
options(knitr.kable.NA = 0)
knitr::kable(sum_stat, 
             col.names=c("Observations", "Mean", "Standard Deviation", "Minimum", "Maximum"),
             format.args = list(big.mark=","), 
             caption = "Insurance Plan Summary Statistics",
             booktabs = TRUE) %>%
  kable_styling(latex_options = c("hold_position"))
```

```{r, include=FALSE}
health_stats
```

```{r table2, include=T, eval=T, echo=F}
options(knitr.kable.NA = 0)
knitr::kable(health_stats, 
             col.names=c("Health Plan", "Medicaid Expansion", "Average Health Status"),
             format.args = list(big.mark=","), 
             caption = "Average Health Status Ratings",
             booktabs = TRUE) %>%
  kable_styling(latex_options = c("hold_position"))
```

```{r fig1, include=T, eval=T, echo=F, fig.cap="Share of Uninsured Population"}
fig1
```

```{r fig2, include=T, eval=T, echo=F, fig.cap="Share of Insurance Distribution"}
fig2
```

```{r fig3, include=T, eval=T, echo=F, fig.cap="Self Reported Health Status, before and after, Medicaid Expansion "}
fig3
```

```{r fig4, include=T, eval=T, echo=F, fig.cap="Self Reported Health Status and Health Care Coverage"}
fig4
```

